version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:latest
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"  
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
      - "9092:9092"  # Required for SonarQube to communicate with PostgreSQL
    
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-db:5432/sonarqube
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=sonarqube
      - SONARQUBE_WEB_CONTEXT=/sonar
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-extensions:/opt/sonarqube/extensions
      - sonarqube-plugins:/opt/sonarqube/lib/bundled-plugins

  sonarqube-db:
    image: postgres:12
    
    environment:
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarqube
      - POSTGRES_DB=sonarqube
    volumes:
      - sonarqube-db-data:/var/lib/postgresql/data

networks:
  sonarqube-network:

volumes:
  jenkins_home:
    external: true
  sonarqube-data:
  sonarqube-extensions:
  sonarqube-plugins:
  sonarqube-db-data:
